version: "3"
services:
  db:
    image: mysql:latest
    container_name: ${DB_CONTAINER_NAME}
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    # volumes:
    #   - ./data:/var/lib/mysql
    ports:
      - 3306:3306

  backend:
    image: qrganize-backend
    container_name: qrganize-backend
    build:
      context: ../services/backend
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
    ports:
      - "3000:3000"
    depends_on:
      - db
