version: "3"
services:
  db:
    extends:
      file: docker-compose.yaml
      service: db

  backend:
    image: qrganize-backend-dev
    container_name: qrganize-backend-dev
    build:
      context: ../services/backend
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ../services/backend:/app
      - /app/node_modules
